name: Deploy Web App - Backend

on:
  push:
    branches:
      - main  # O la rama que utilizas para la producción
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  webserver-1:
    runs-on: 11703  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 20.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run script file
        run: |
          cd api
          echo MONGO_URL="mongodb+srv://admin:T9ud6IkaljkQQrA2@moneytracker.pmedkyg.mongodb.net/?retryWrites=true&w=majority&appName=moneytracker" > .env
          pm2 start app.js
          pm2 save
        shell: bash
  
  webserver-2:
    runs-on: 31133  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 16.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install

      - name: Run script file
        run: |
          cd api
          echo MONGO_URL="mongodb+srv://admin:T9ud6IkaljkQQrA2@moneytracker.pmedkyg.mongodb.net/?retryWrites=true&w=majority&appName=moneytracker" > .env
          pm2 start app.js
          pm2 save
        shell: bash
