name: Deploy Web App - Backend

on:
  push:
    branches:
      - main  # O la rama que utilizas para la producción
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  webserver-1:
    runs-on: 24226  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 20.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install
      
      - name: Run the scripts
        run: |
          NODE_PORT=4000 pm2 start -i 0 ./api/index.js --name moneytrackerapi
  
  webserver-2:
    runs-on: 26947  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 16.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install

      - name: Run the scripts
        run: |
          NODE_PORT=4000 pm2 start -i 0 ./api/index.js --name moneytrackerapi