name: Deploy Web App - Backend

on:
  push:
    branches:
      - main  # O la rama que utilizas para la producción
    paths:
      - 'api/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  webserver-1:
    runs-on: 11703  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 20.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install
      
      - run: npm install pm2@latest -g #install pm2 global
      - run: pm2 -V #check pm2 version
      - run: pm2 list #check pm2 list
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start api/index.js --watch -i max
  
  webserver-2:
    runs-on: 31133  # Etiqueta de tu runner auto-hospedado
    steps:
      - uses: actions/checkout@v3
      
      # The second step sets up Node.js with version 16.
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install

      - run: npm install pm2@latest -g #install pm2 global
      - run: pm2 -V #check pm2 version
      - run: pm2 list #check pm2 list
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start api/index.js --watch -i max